# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc0ce540f6320e8d4a618f86c3a47132ab855309dd694291af3107439ff702d2d1da11a71cc04bace2a4d4c290b3ab8dc66792887119b144c0e23c8d5b580624

test:
  secret_key_base: 36aab37c8c982b8c9e21a378b8fec21799e61cbb20202efef4db7c965d3d90a7f6f2629d93c7504e2d96d8b1eb08185c018e845445fc4c77e8c2d66f934a8f13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
